-   id: absolufy-imports
    name: absolufy-imports
    description: Automatically remove string literals in type annotations.
    entry: absolufy-imports
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
